import Head from "next/head";
import { useState } from "react";
import { ColorInput, TextInput } from "@/components/Input/Input";
import $ from "jquery";
import Darkmode from "darkmode-js";

export default function Home() {
  const options = {
    bottom: '64px', // default: '32px'
    right: 'unset', // default: '32px'
    left: '32px', // default: 'unset'
    time: '0.5s', // default: '0.3s'
    mixColor: '#ccc', // default: '#fff'
    backgroundColor: '#fff',  // default: '#fff'
    buttonColorDark: '#100f2c',  // default: '#100f2c'
    buttonColorLight: '#fff', // default: '#fff'
    saveInCookies: false, // default: true,
    label: '🌓', // default: ''
    autoMatchOsTheme: true // default: true
  }
  const darkmode = new Darkmode(options);
  darkmode.showWidget();
  // darkmode.toggle();
  const [imgUrl, setImgUrl] = useState("./img/default/qr-placeholder.png");
  const [downloadUrl, setDownloadUrl] = useState("./img/default/qr-placeholder.png");

  const hexToDecimal = hex => parseInt(hex, 16);

  const hexToRGB = hex => {
    let red, green, blue;

    red = hexToDecimal(hex[1] + "" + hex[2]);
    green = hexToDecimal(hex[3] + "" + hex[4]);
    blue = hexToDecimal(hex[5] + "" + hex[6]);
    return red + "-" + green + "-" + blue;
  }

  const qrRequest = () => {
    let parametersJson = {
      size: 250,
      backgroundColor: "255-255-255",
      qrColor: "00-00-00",
      padding: 2,
      data: "dev.to",
      download: 1,
    };

    let parameters;

    let input = $("#qr-input");
    let colorInput = $(".qr-color");
    let bgcolorInput = $(".qr-bgcolor");
    let button = $("#qr-submit");
    let download = $("#qr-download");

    parametersJson.data = input.val() || "";

    parametersJson.qrColor = hexToRGB(colorInput.val());
    parametersJson.backgroundColor = hexToRGB(bgcolorInput.val());

    if (parametersJson.data !== "") {
      parameters = `size=${parametersJson.size}&bgcolor=${parametersJson.backgroundColor}&color=${parametersJson.qrColor}&qzone=${parametersJson.padding}&data=${parametersJson.data}`; // Stitch Together all Paramenters
      button.text("Re-generate");
      download.show();
      setDownloadUrl(
        `https://api.qrserver.com/v1/create-qr-code/?${parameters}&download=1`
      );
      setImgUrl(`https://api.qrserver.com/v1/create-qr-code/?${parameters}`);
    } else {
      button.text("Generate");
      download.hide();
      setImgUrl("./img/default/qr-placeholder.png");
    }
  }

  return (
    <>
      <Head>
        <title>QR-Code Generator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container">
        <div className="title">QR-Code Generator</div>
        <div className="description">
          By ZYXMA
        </div>
        <TextInput id="qr-input" placeholder="Link or text here" />
        <ColorInput
          label="Color: "
          className="qr-color"
          id="qr-color"
          base="#000000"
        />
        <ColorInput
          label="Background Color: "
          className="qr-bgcolor"
          id="qr-bgcolor"
          base="#ffffff"
        />
        <button className="submitBtn" id="qr-submit" onClick={qrRequest}>
          Generate
        </button>
        <a
          href={downloadUrl}
          target="_blank"
          rel="noreferrer"
          id="qr-download"
          className="downloadBtn"
          style={{ display: "none" }}
        >
          <em className="fa fa-download"></em> Download
        </a>
        <img
          id="qr-image"
          src={imgUrl}
          alt="QRcode must generate here."
        />
      </main>
    </>
  );
}
